### PR TITLE
Fix #194 on deprecated message for Real(FloatDP)

### LINKED ISSUE #194: DEPRECATED message when building an empty RealInterval
The following message is issued once when building an empty or infinite interval:

```c++
DEPRECATED: Function "Real::Real(FloatDPValue)" is deprecated. "Use Real([Exact]Double) or Real(Dyadic) instead."
```

This situation happens commonly during evolution, so this is not the user's fault and shall be addressed. 
Currently the implementation for Interval<U> uses the global FloatDP infty variable. We shall rather supply a U::inf() symbol consistently throughout the library.

### PR DESCRIPTION
**Pull request by lgeretti**

### CODE REVIEW

**Comment by lgeretti** [comment]
Incorrectly targeted master.

**Comment by lgeretti** [comment]
Closed since it merged incorrectly into master, but I should just have changed the target since that is possibly using the Edit button.

**Comment by pietercollins** [comment]
The commit with message:
    [TEMPORARY] Added -Wshadow flag for compilation 
should be removed

**Comment by lgeretti** [comment]
If you are ok with it, I can reword the commit message (-Wshadow is here to stay, actually, so we just have to remove the [TEMPORARY] prefix) and force push.

**Comment by pietercollins** [comment]
That's best if we are keeping the commit.


________________________________

**Pull request closed without merging**
